// <auto-generated />
namespace DOAN_WEBNC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _InitialDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_InitialDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202007160901453__InitialDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
